# secrets.toml

[connections.snowflake]
account = "PHILYGM-JH08241"
user = "YAKOUBI95"
password = "Amazigh02072024"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
